### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by eclairevoyant** [toasterllc/debase#6]
We were looking into packaging this [for nixpkgs](https://github.com/NixOS/nixpkgs/issues/317240) but currently we are unsure how the project is permitted to be used.

https://toaster.llc/debase/index.html mentioned that this is open-source, but we don't see a license mentioned. Would you consider adding an explicitly open-source license (GPL3, MIT, BSD, etc.)?

**Comment by davetoaster** [comment]
Thanks @eclairevoyant, I just added `LICENSE.md` (public domain).
